# fly.toml file generated for ntp on 2023-05-14T13:41:16-04:00

app = "ntp"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  web = "bin/ntp-report"
  ntp = "bin/ntp"

[env]
  NTP_PORT = "123"
  NTP_HOST = "fly-global-services"
  REPORT_PORT = "8080"
  ENABLED = "1"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 123
  protocol = "udp"
  processes = ["ntp"]

  [[services.ports]]
    port = 123

[[services]]
  http_checks = []
  internal_port = 8080
  min_machines_running = 0
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
